# Generated by Django 2.2.7 on 2020-01-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='dry_clean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dry+', to='laundry.Service'),
        ),
        migrations.AlterField(
            model_name='item',
            name='iron',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iron+', to='laundry.Service'),
        ),
        migrations.AlterField(
            model_name='item',
            name='laundry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laundry+', to='laundry.Service'),
        ),
        migrations.DeleteModel(
            name='DryClean',
        ),
        migrations.DeleteModel(
            name='Iron',
        ),
        migrations.DeleteModel(
            name='Laundry',
        ),
    ]
