# Generated by Django 2.2.7 on 2020-02-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0004_auto_20200122_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
