# Generated by Django 2.2.7 on 2020-03-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0006_orderitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
    ]
