# Generated by Django 2.2.7 on 2020-03-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0008_userorder_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='total',
        ),
    ]
