# Generated by Django 2.2.7 on 2020-03-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0009_remove_userorder_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
