# Generated by Django 2.2.7 on 2020-03-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0012_auto_20200311_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
